version: '2'
services:
  mariadb:
    image: hbars/tlpsmariadb:1.0
    ports:
      - '3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=12345678
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  testlink:
    image: docker.io/bitnami/testlink:1
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - TESTLINK_DATABASE_HOST=mariadb
      - TESTLINK_DATABASE_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=root
      - TESTLINK_DATABASE_PASSWORD=12345678
      - TESTLINK_USERNAME=user
      - TESTLINK_PASSWORD=bitnami
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'testlink_data:/bitnami/testlink'
    depends_on:
      - mariadb
  app:
    image: pservice
    build: .
    #command: bash -c "php artisan migrate:refresh --seed && apache2 -DFOREGROUND"
    env_file:
      - .env
    ports:
      - "5000:80"
    # volumes:
    #   - .:/app
volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
